development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:7bb17d545ea387becdce9644f51573f1@angelfish.redistogo.com:10020/
  channel_prefix: pop-roulette_production
