# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1bbcd286ca9f81e843957d25cb10a330e08233263dcd5d2ba1b5454a3a9118cb534f3a9720a0b76dd0a40006a107f17d18f68774b39f192a9c422a2d4e99818c

test:
  secret_key_base: fc2deb18dbd29dda0d473b07a6647576faf256126852ae914cc05606c6583ace83bcb6252a5881e8af65c2c9c5e5729a028a63acdf844db3cd81bc536659a99e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
